### ISSUE TITLE
【秀场直播】【5.0.0】由 onLocalAudioStats、onRemoteAudioStats 回调驱动连麦、pk画面中麦克风图标状态变化

### ISSUE THREAD

**Issue by HugoChaan** [AgoraIO-Usecase/agora-ent-scenarios#984]
onLocalAudioState、onRemoteAudioState 需要打印日志 便于问题调查

**Comment by xgfd3** [comment]
1. 回调修正 
onLocalAudioStats -> onAudioPublishStateChanged
onRemoteAudioStats -> onRemoteAudioStateChanged

2. 因为开关音量是通过muteLocalAudioStreamEx实现，onLocalAudioStateChanged无法收到本地音量变化，需要改成onAudioPublishStateChanged
